"use strict";
exports.__esModule = true;
exports.puntoorigen2 = exports.puntoorigen = exports.punto = void 0;
var punto_1 = require("./punto");
var triangulo_1 = require("./triangulo");
exports.punto = new punto_1.Punto(10, -5);
exports.puntoorigen = new punto_1.Punto(0, 0);
exports.puntoorigen2 = new punto_1.Punto(10, 10);
var otroPunto = new punto_1.Punto(20, 10);
var puntitos = [exports.puntoorigen, exports.puntoorigen2, otroPunto];
console.log(exports.puntoorigen.toString());
console.log(exports.puntoorigen.distanciaAlOrigen());
console.log(exports.punto.calcularCuadrante());
console.log(exports.punto.calcularDistancia(exports.puntoorigen));
console.log(exports.punto.calcularMasCercano(puntitos));
//TRIANGULO 
var punto1 = new punto_1.Punto(4, 3);
var punto2 = new punto_1.Punto(7, 5);
var punto3 = new punto_1.Punto(9, 2);
var trian = new triangulo_1.Triangulo(punto1, punto2, punto3);
console.log(trian.calcularLongitudLados());
